name: Terraform Apply GKE

on:
  push:
    branches: 
      - develop
    paths:
      - Terraform/**

jobs:
  terraform-apply-gke-develop:
    if: startsWith( github.ref, 'refs/heads/feature/' ) || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: develop
    defaults:
      run:
        shell: bash
    env:
      GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
      GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      
      - name: Checkout LFS objects
        run: git lfs pull

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info
      
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.15.4 
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./Terraform/env/develop"
          tf_actions_comment: true

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.15.4 
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./Terraform/env/develop"
          tf_actions_comment: true
          args: "--var-file=develop.tfvars"
        